### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by ghost** [EthanSchatzline/DrawableView#8]
How can i add an image as background and draw over it?

**Comment by EthanSchatzline** [comment]
@jasso1 you can add a UIImage to your viewcontroller, then add the DrawableView on top, and set the background color to clear.

**Comment by omerjanjua** [comment]
@EthanSchatzline So I have a UIImageView on top of that I have the DrawableView and I can draw on it. What is the best way to save the modified image? I was thinking screenshot, but there must be a better way

**Comment by omerjanjua** [comment]
I fixed it by creating a UIView. Adding the UIImageView and DrawableView as a subview. Then convert the parent view into an image using this function https://stackoverflow.com/a/4334902/1303176
